default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: lucas2018
  host: localhost
  port: 5432

development:
  <<: *default
  database: finance_api_development

test:
  <<: *default
  database: finance_api_test

production:
  <<: *default
  database: finance_api_production
  username: postgres
  password: <%= ENV['FINANCE_API_DATABASE_PASSWORD'] %>
