default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: finance_api_development
  username: lucas
  password: lucas2018

test:
  <<: *default
  database: finance_api_development
  username: lucas
  password: lucas2018

production:
  <<: *default
  database: finance_api_production
  username: finance_user
  password: <%= ENV['FINANCE_DATABASE_PASSWORD'] %>
